"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Smit Chaudhary"
email = "smitchaudhary10@gmail.com"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
e = ["edit"]
pull = ["git", "fetch"]
push = ["git", "push"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

[remotes.origin]
auto-track-bookmarks = "glob:*"

[ui]
default-command = "log"
diff-editor = ":builtin"
merge-editor = ":builtin"
editor = "vim"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[[--scope]]
--when.repositories = ["~/Documents/Foyer"]
[--scope.user]
email = "smit@foyer.work"
[--scope.signing]
key = "~/.ssh/id_ed25519_foyer.pub"
